spring:
  profiles:
    active: test
  aop:
    auto: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: clinic
  http:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 1MB
      max-request-size: 2MB

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

session:
  timeout: 3000000