spring:
  profiles:
    active: test
  aop:
    auto: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: clinic

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

session:
  timeout: 3000000