spring:
  profiles:
    active: dev
  aop:
    auto: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: Denture-Factory
  http:
      multipart:
        file-size-threshold: 50MB
        max-file-size: 50MB
        max-request-size: 1024MB