server:
  port: 8080
spring:
    datasource:
        url: jdbc:mysql://106.14.237.27:3306/liyou?useUnicode=true&characterEncoding=utf-8&useSSL=false # mysql server url
        username: liyou
        password: abc123
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 200
        test-on-borrow: true
        test-while-idle: true
        validation-query: 'select 1'

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.yuzi.denture: DEBUG
  file: log/denture.log