server:
  port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/denture?useUnicode=true&characterEncoding=utf-8&useSSL=false # mysql server url
        username: root
        password: jingle2534688
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 200
        test-on-borrow: true
        test-while-idle: true
        validation-query: 'select 1'

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.yuzi.denture: DEBUG
  file: log/denture.log

avatar:
  location: D:\r_workspace\test_dir\avatar
logo:
  location: D:\r_workspace\test_dir\logo